phraseapp: 
  access_token: 80abf10576e77936022717f0706502cca61125953ac21f17661ec187efcce0ed
  file_format: json
  project_id: 7a9e7f65cc179ce2a8d625232e7f7042
  pull: 
    targets: 
      - file: ./i18n/de/locale.json
      - file: ./i18n/fr/locale.json
      - file: ./i18n/nl/locale.json
  push: 
    sources: 
      - file: ./i18n/de/resource.json
        params: 
          locale_id: 55f47efa7977f201a8aa253208483212
          update_translations: true
      - file: ./i18n/nl/resource.json
        params: 
          locale_id: 53a422b8c790e88eca3bb84d8ca98a52
          update_translations: true
      - file: ./i18n/fr/resource.json
        params: 
          locale_id: 50c91ae8bfb062ac437d531b1ff8dd8c
          update_translations: true
