phraseapp: 
  access_token: 80abf10576e77936022717f0706502cca61125953ac21f17661ec187efcce0ed
  file_format: react_simple_json
  project_id: 7a9e7f65cc179ce2a8d625232e7f7042
  pull: 
    targets: 
      - file: ./i18n/en/translation.json
        params: 
          locale_id: 556450dfae1fe937e0798bda63223566
          update_translations: false
      - file: ./i18n/de/translation.json
        params: 
          locale_id: 5d1242900dbc846e78854ed9343f68ae
          update_translations: false
      - file: ./i18n/fr/translation.json
        params: 
          locale_id: f8b3bb5e9e7e175873f15a0a41d2b611
          update_translations: false
      - file: ./i18n/nl/translation.json
        params: 
          locale_id: 38e370118ae8bdf9f8fed68397f617de
          update_translations: false
      - file: ./i18n/it/translation.json
        params: 
          locale_id: 6ad5cbbf0d61bf0cf03db0de6c1f1951
          update_translations: false
      - file: ./i18n/ar/translation.json
        params: 
          locale_id: 680d94d98f55ebf56f9dd59c45d6dcfa
          update_translations: false
  push: 
    sources:
      - file: ./i18n/en/translation.json
        params: 
          locale_id: 556450dfae1fe937e0798bda63223566
          update_translations: false
      - file: ./i18n/de/translation.json
        params: 
          locale_id: 5d1242900dbc846e78854ed9343f68ae
          update_translations: false
      - file: ./i18n/fr/translation.json
        params: 
          locale_id: f8b3bb5e9e7e175873f15a0a41d2b611
          update_translations: false
      - file: ./i18n/nl/translation.json
        params: 
          locale_id: 38e370118ae8bdf9f8fed68397f617de
          update_translations: false
      - file: ./i18n/it/translation.json
        params: 
          locale_id: 6ad5cbbf0d61bf0cf03db0de6c1f1951
          update_translations: false
      - file: ./i18n/ar/translation.json
        params: 
          locale_id: 680d94d98f55ebf56f9dd59c45d6dcfa
          update_translations: false

